### ISSUE TITLE
broken link to pypulseq spec

### ISSUE THREAD

**Issue by grlee77** [imr-framework/pypulseq#10]
There are several broken links in the [README.md as rendered by GitHub](https://github.com/imr-framework/pypulseq). For example, the `Pulseq` spec directs me to:
https://github.com/imr-framework/pypulseq/blob/master/pulseq-spec
which does not exist

However, at the bottom of the [raw file](https://raw.githubusercontent.com/imr-framework/pypulseq/master/README.md) it looks like a working link is correctly specified:
http://pulseq.github.io/specification.pdf

I think the issue is that Markdown is expecting a square bracket around the link variable name.
e.g. `[Pulseq specification](pulseq-spec)` should be `[Pulseq specification][pulseq-spec]`, etc.

**Comment by sravan953** [comment]
Thank you, will look into this and fix it!

**Comment by sravan953** [comment]
Closed in 86a31ae568cc408f0ad9558ed2e1db5539ecdd82.

**Comment by grlee77** [comment]
thanks!
