### ISSUE TITLE
duplicate argument in make_arbitrary_rf.py

### ISSUE THREAD

**Issue by rextlfung** [imr-framework/pypulseq#104]
There are two "return_delay" arguments in the function definition which raised an error when importing PyPulseq

**Comment by sravan953** [comment]
Hi, can you please elaborate? Which version are you installing? Via `pip`? Which script are you attempting to run?

**Comment by nnmurthy** [comment]
This should be fixed now in the latest version of dev (I changed this along with a couple of other bugs in the example jupyter notebook).

**Comment by rextlfung** [comment]
Hi, sorry for not providing more details. I meant the latest version of dev but I believe @nnmurthy has already fixed the issue. Thank you!
