### ISSUE TITLE
'Sequence' object has no attribute 'gradient_waveforms' in Sequence.calculate_kspace

### ISSUE THREAD

**Issue by fzimmermann89** [imr-framework/pypulseq#107]
Hi,

https://github.com/imr-framework/pypulseq/blob/a18e34f89bc1d9a4a30e467013be00a8f17a3439/pypulseq/Sequence/sequence.py#L214
results in '`Sequence' object has no attribute 'gradient_waveforms'`
as `gradient_waveforms` has been removed in https://github.com/imr-framework/pypulseq/commit/22fb57c2006208510d0fd573fc6757d71fbae4c8

Not sure why as I am not familiar with  thecodebase and the commit message does not really explain it... 

Cheers,
Felix

**Comment by sravan953** [comment]
Hello, can you share code to reproduce this bug?

**Comment by fzimmermann89** [comment]
Yes,
any call to  `calculate_kspace` will cause the error. The minimal example is 
```
import pypulseq as pp
pp.Sequence().calculate_kspace()
```

**Comment by bilal-tasdelen** [comment]
@sravan953 @fzimmermann89 I believe `calculate_kspace` is also non-functional in upstream `Pulseq` implementation. I am not sure why.

@sravan953 Was there a reason to remove `gradient_waveforms` function? There are still several cases where it is useful. We can also take it out from `Sequence.m` and put into another file, if complexity is the issue.

**Comment by fzimmermann89** [comment]
..and is `calculate_kspacePP` a drop-in replacement for `calculate_kspace`?

**Comment by sravan953** [comment]
@bilal-tasdelen @fzimmermann89 `calculate_kspacePP()` is supposed to be the replacement for `calculate_kspace()`. Since `gradient_waveforms()` was only called by `calculate_kspace()`, I removed it!

**Comment by fzimmermann89** [comment]
As https://pypulseq.readthedocs.io/en/master/pypulseq.Sequence.html#pypulseq.Sequence.sequence.Sequence.calculate_kspace 
calculate_kspace  is still in the documentation, I would prefer to get this fixed again.

Sorry for dropping the ball here, but I did not use pypulseq for some time -- and today got hit again by the same issue.
