### ISSUE TITLE
Loosen pinning of numpy & matlplotlib versions in setup.py

### ISSUE THREAD

**Issue by grlee77** [imr-framework/pypulseq#12]
**Is your feature request related to a problem? Please describe.**

Dependencies are pinned too tightly. It would be best to not force users to install a specific micro release of both NumPy and Matplotlib to install pypulseq. As Numpy is at the base of the scientific python ecosystem, we should attempt not to require users to change their version unless strictly necessary. 

Similarly, I see that the package is listed as Python 3.6 only in `setup.py`, but it seems to also work for 3.7, so that should probably be added as well. (I see there are some modern code features like type annotations that may prevent use of earlier versions).

**Describe the solution you'd like**
It would be better to identify a minimum version (or version range) that are compatible with pypulseq. Matplotlib seems to be only needed for the plotting capabilities and could potentially be converted to an optional runtime requirement.

**Describe alternatives you've considered**

**Additional context**

**Comment by sravan953** [comment]
Thank you for your input. We advise users to install using a virtual environment, so we thought it acceptable to specify x.y.z versioning for dependencies. Will change in further commits.
