### ISSUE TITLE
dev branch: write_gre.py gives: invalid value encountered in true_divide   slice_pos[j] = np.divide(

### ISSUE THREAD

**Issue by Nikbert** [imr-framework/pypulseq#120]
**Describe the bug**
/sequence.py:404: RuntimeWarning: invalid value encountered in true_divide
  slice_pos[j] = np.divide(

**To Reproduce**
- I installed a fresh dev branch and get the RuntimeWarning mentioned above when running python "write_gre.py"  in "pypulseq/pypulseq/seq_examples/scripts"
- the other write_seq examples seem to work fine.

**Comment by bilal-tasdelen** [comment]
Hi @Nikbert. This is just a warning. Do you see any unusual thing with the resulting sequence?
