### ISSUE TITLE
unused variable

### ISSUE THREAD

**Issue by maddin200** [imr-framework/pypulseq#136]
make_block_pulse.py line 78

Code:
 BW = 1 / (4 * duration) <-- unused further on

**Comment by sravan953** [comment]
Hi @maddin200 , thanks for opening this issue. Since this is not a breaking bug, it is low-priority for now. In the meanwhile, feel free to submit a PR to the dev branch!

**Comment by wtclarke** [comment]
This is something I've fixed in #151, so this can be closed one that is merged.

**Comment by wtclarke** [comment]
With the merge of #151, this issue can be closed.
