### ISSUE TITLE
np.int and np.float

### ISSUE THREAD

**Issue by sairamgeethanath** [imr-framework/pypulseq#138]
**Describe the bug**
Instance of np.int and np.float raise exceptions

**To Reproduce**
run pypulseq libraries that compute timing events using a declaration of int and float

**Expected behavior**
AttributeError: module 'numpy' has no attribute 'int'.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - OS Version:13.5.1 (22G90)
- `pypulseq` version: 1.4.0

**Additional context**

**Comment by btasdelen** [comment]
Hi @sairamgeethanath. There is no `np.int` and `np.float` should have left in the code base, they are converted to `np.float64` and `np.int32`, as the former are deprecated: #115. I double-checked the code base and did not find any. Is it possible that you are using an old version of PyPulseq? If not, can you point out which function throws the error?
