### ISSUE TITLE
Arguments of make_block_pulse are highly confusing 

### ISSUE THREAD

**Issue by wtclarke** [imr-framework/pypulseq#149]
`bandwidth`, [the second listed argument (default=0)](https://github.com/imr-framework/pypulseq/blob/dev/pypulseq/make_block_pulse.py#L14) has no effect (see [relevant logic](https://github.com/imr-framework/pypulseq/blob/dev/pypulseq/make_block_pulse.py#L70)),  unless the the default to `duration` ([default = 4E-3](https://github.com/imr-framework/pypulseq/blob/dev/pypulseq/make_block_pulse.py#L16)) is overwritten by the user. This isn't documented anywhere, no warning is issued, and `duration` is listed several places below `bandwidth` in the list of arguments.

**Comment by sravan953** [comment]
Thanks for this, @wtclarke ! Would you be interested in submitting a PR wherein a warning is raised?

**Comment by wtclarke** [comment]
Done in #151 . I've also added markers for the tests, so only the tests we expect to work will run.

**Comment by wtclarke** [comment]
Closed in #151
