### ISSUE TITLE
more pythonic file organization

### ISSUE THREAD

**Issue by grlee77** [imr-framework/pypulseq#15]
**Is your feature request related to a problem? Please describe.**

This is a low priority issue and ultimately a matter of taste, but I thought I would offer it for consideration.

The files in `pypulseq` seem to be nearly a 1:1 mapping of the corresponding Matlab files from `pulseq`. It would perhaps be more Pythonic to group related functions into a single file rather than having one file per function.

**Describe the solution you'd like**

As a concrete example, the RF pulse generating functions:
    make_arbitrary_rf
    make_gauss_pulse
    make_sinc_pulse
    make_block_pulse
could be grouped within a single module called `rf.py`.

Similarly, several gradient related files could be merged into something like `grad.py`

**Describe alternatives you've considered**

**Additional context**

**Comment by sravan953** [comment]
@grlee77 Thank you for your inputs. The 1:1 mapping was purely intended to provide familiarity to users jumping from Matlab. What do you think about `rf` and `grad` sub-packages instead of modules? I can imagine that a single `rf.py` module would be not so pretty to look at.

**Comment by grlee77** [comment]
I am not saying you have to make any change here, it was just a suggestion. In your case, it may be beneficial to continue to mirror the structure of the Matlab code if you anticipate most users are migrating from Matlab and are more familiar with that structure. In that case, just go ahead and close this issue.

> I can imagine that a single rf.py module would be not so pretty to look at.

I don't really agree. For Python projects, it is very common to group several related functions together in a single file. As a concrete 3rd party example, see the [imports at the top of __init__.py for the filters submodule of scikit-image](https://github.com/scikit-image/scikit-image/blob/master/skimage/filters/__init__.py). Here there are several files within the `filters` folder, some of which have several functions internally, but they are grouped in a logical manner (e.g. edges vs. thresholding). To me, that seems better than if every individual function in that module were stored in its own file.

**Comment by sravan953** [comment]
Thanks for sharing the scikit-image example, I suppose we will stick to the MATLAB convention to ensure familiarity. Once again, thanks for your insights, I learnt something new.
