### ISSUE TITLE
adding a test suite and continuous integration

### ISSUE THREAD

**Issue by grlee77** [imr-framework/pypulseq#16]
**Is your feature request related to a problem? Please describe.**
In considering the JOSS review criteria, I think the lack of a test suite or any type of continuous integration to verify correct operation across platforms / software versions is the biggest weakness.

There are fortunately a number of demos that the user can run to verify the basic operation of the package, but I did see any automated way to run tests.

**Describe the solution you'd like**

Ideally some automated unit tests would be created. The [pytest](https://docs.pytest.org/en/latest/) package is a popular choice for this.

Once unit tests have been defined, services like Travis-CI, Circle-CI, Appveyor and/or Azure can be used to set up automated cross-platform testing on each pull request, etc. This may be overkill at the moment for a project of this size, but something to keep in mind.

**Describe alternatives you've considered**

**Additional context**

**Comment by sravan953** [comment]
@grlee77 Thank you for your comments regarding automated testing/CI. We have been discussing this internally and plan to incorporate the same in our next major release (2.0.0) as a part of ISMRM 2021 efforts.

**Comment by sravan953** [comment]
@grlee77 Can this issue be closed?

**Comment by grlee77** [comment]
It does not hurt to keep the issue open as a reminder to add this in the future. You could remove the "review comment" label and add a label like "task" to indicate that the issue is task-related and not a bug. Ultimately, it is up to you whether you find it useful to keep this open or not, though.

**Comment by sravan953** [comment]
Completely on board about the benefits of CI - will incorporate it in the future, thank you for your inputs.

**Comment by schuenke** [comment]
Was added in #144 , #173 , #207 , ... so I close this. Feel free to re-open it if needed.
