### ISSUE TITLE
Shape check for arbitrary rf/grad

### ISSUE THREAD

**Issue by Mmj94** [imr-framework/pypulseq#22]
**Is your feature request related to a problem? Please describe.**
If a waveform of shape (1,x) is used to construct arbitrary rf or gradient events they cannot be successfully added to a block.

**Describe the solution you'd like**
Perform shape checking

**Comment by sravan953** [comment]
Could you share code to reproduce this?

**Comment by Mmj94** [comment]
<pre>
`from pypulseq.opts import Opts  
from pypulseq.Sequence.sequence import Sequence
from pypulseq.make_arbitrary_rf import make_arbitrary_rf

import numpy as np
import math

system = Opts(max_grad=32, grad_unit='mT/m', max_slew=130, slew_unit='T/m/s', grad_raster_time=10e-6, rf_raster_time= 10e-6)
seq = Sequence(system)

rf = np.ones((1, 300), dtype=complex)
#rf = np.ones((300, 1), dtype=complex)

rf_waveform, _ = make_arbitrary_rf(flip_angle=90 * 180 / math.pi, system=system, signal=rf)
seq.add_block(rf_waveform)`
<pre>

**Comment by Mmj94** [comment]
Running the code above as it is, it would break.
However, if you run the second rf line instead that is now commented, it will go through.

**Comment by sravan953** [comment]
Thank you! Commit 0f55671aaa41beb5bc56c39e3c437aed31fcbc1a should have fixed this. Please let me know so I can close the issue.

**Comment by Mmj94** [comment]
Yes, this fixes the above problem. You can close the issue.
