### ISSUE TITLE
Output sequence waveforms from .seq files

### ISSUE THREAD

**Issue by tonggehua** [imr-framework/pypulseq#29]
**Enhancement Description**
It would be helpful to be able to output entire waveforms (i.e. all blocks concatenated together) for:

- RF Magnitude
- RF Phase
- Gx
- Gy
- Gz
- ADC points
- Time 

**Describe the solution you'd like**
A Class function for seq objects. 
It would be nice to be able to specify (1) Time range and (2) Block index range for custom outputs for examination and debugging.

**Describe alternatives you've considered**
N/A

**Comment by sairamgeethanath** [comment]
1. csv file format for spectrometer
2. Separate files for RF and Gradients and a way to combine them and delay periods

**Comment by sravan953** [comment]
@tonggehua For gradient waveforms, `pypulseq` has the [`seq.gradient_waveforms()`](https://github.com/imr-framework/pypulseq/blob/595351bc38ed0b57a359c4aa12d6b38c5b88f6d0/pypulseq/Sequence/sequence.py#L326) method. Let me know if that's sufficient for gradient waveforms.

**Comment by tonggehua** [comment]
@sravan953 
Right now, everyone will have to write their own code for outputting the entire waveforms. It would be valuable to have an inbuilt method for it. Plus, it might just be a simple modification from seq.plot().

**Comment by sravan953** [comment]
@tonggehua If you have a `seq` object, call `seq.gradient_waveforms()` to get the gradient waveforms across the three channels. Does that clarify what the method does?

**Comment by tonggehua** [comment]
@sravan953 It does output the entire gradient waveforms. So what we need is adding on the RF, ADC, and uniform timing across. Thanks!

**Comment by sravan953** [comment]
@tonggehua Yes, thanks for confirming! Will work on the RF and ADC. Could you elaborate on what you mean by 'uniform timing'? Thanks again.

**Comment by sairamgeethanath** [comment]
I would not recommend uniform timing. I would recommend event-based timing. I do not see value in having times for delays (0s), only start and stop should suffice. If we need a common time clock, that will run at 1us and can be quite lengthy and redundant.

**Comment by tonggehua** [comment]
@sairamgeethanath For compression and storage, uniform timing is definitely not efficient. The feature I am suggesting is having flattened outputs that share the same time vector for  (1) easy plotting and (2) benchmarking (comparing one sequence to another) purposes.

**Comment by sairamgeethanath** [comment]
@tonggehua Not efficient for plotting too. I need two endpoints to connect and make a straight line. Even from a console standpoint, you just sample value and HOLD until it changes: either for writing or for reading.

**Comment by tonggehua** [comment]
@sairamgeethanath @sravan953 For the .seq waveform output feature, I would like to use it for more robust benchmarking of seq2xml. JEMRIS's output is uniformly timed across RF, G, and ADC. I would like to be able to compare the .h5 output and seq.output_waveforms(), say, directly. Having the same time resolution (maybe Δt should be user-specifiable) helps.

**Comment by sairamgeethanath** [comment]
@tonggehua @sravan953 This feature needs to return two outputs: one should be in the format compatible with JEMRIS (@tonggehua please share a sample for gre with @sravan953 ).  The other output should be compatible with the console needs of event-based logging only.

**Comment by sravan953** [comment]
@tonggehua Commit f36f91a7dd7ff7c0b37ce0f559312c918f63afe4 contains an updated `waveforms_and_times()` method - https://github.com/imr-framework/pypulseq/blob/cc4aa8d4a50b2a17d4e375306d5d322e70ceac75/pypulseq/Sequence/sequence.py#L1096.
Let me know if it's what you were looking for?

**Comment by sravan953** [comment]
@tonggehua Alright will wait for your feedback.

**Comment by sravan953** [comment]
PR #62 takes care of this, closing!
