### ISSUE TITLE
t_factor is missing in the ADC plot

### ISSUE THREAD

**Issue by mavel101** [imr-framework/pypulseq#35]
The t_factor for scaling the plot of ADC points is missing in sequence.plot. This results in a wrong scaling of the ADC plot for 'ms' or 'us' representations

**Comment by sravan953** [comment]
Hi! I've just released the [latest version](https://github.com/imr-framework/pypulseq/releases/tag/1.3.1) that fixes this. Please take a look and let me know if I can close this issue. :)
