### ISSUE TITLE
Bug in block length when using arbitrary RF pulses or gradients

### ISSUE THREAD

**Issue by Mmj94** [imr-framework/pypulseq#38]
**Describe the bug**
Sequences won't play when any of the blocks have arbitrary RF or gradients with the same length. Based on trial/error experiments, seems like the gradient waveforms have to have a slightly longer duration compared to the other components of the block (RF pulse signal, adc). 

**To Reproduce**
Create an arbitrary gradient waveform using `make_arbitrary_grad`
Design ADC to have the same number of samples as the gradient created
seq.add_block(gradient,adc)

**Expected behavior**
The sequence won't play with the last version of the interpreter.

**Screenshots**

**Desktop (please complete the following information):**
- `pypulseq` version: 1.2.0.post1

**Comment by sravan953** [comment]
Hi @Mmj94! Is this still an issue?
