### ISSUE TITLE
Functions to make combining gradients easier 

### ISSUE THREAD

**Issue by tonggehua** [imr-framework/pypulseq#41]
**Is your feature request related to a problem? Please describe.**
When I am coding oblique gradients, and with multiple types of gradients being played together, there is a need to add gradients together, scale gradients, or change the channels of an already made gradient object.
* A typical example is when readout, phase encoding, and slice refocusing gradients overlap. It's straightforward when orthogonal encoding is used - each type would corresponding to one channel (either 'x', 'y', or 'z'). However, when you want general oblique encoding, each type has components in x, y, and z. The `add_block` function, however, only accepts one gradient per channel (it overwrites the previous one if more than one is used). 
* Scaling:  in radial k-space readouts, for example, you'd want to scale the x and y gradients while maintaining their shape. Right now, existing sequences simply create new gradients each iteration. It would be nice to have functions dedicated to scaling gradients and changing their channels as part of PyPulseq. 

**Describe the solution you'd like**
Include these utility functions:

1. _Gradient scaling / channel modification_. Returns a changed copy of the input gradient. Detects violations of max gradient or max slew rate and raises corresponding errors. 
2. _Combining any number of gradients with arbitrary channels into 3_: `gx`,`gy`, and `gz`. Preserve trapezoidal gradients if timings match. Otherwise, return general gradients. 
3. _Detect zero gradients during_ `add_block`: don't include them to reduce storage waste
 
**Describe alternatives you've considered**
The alternative is for each user to perform these actions in their custom code, individually. I believe they are generally useful enough to be part of Pypulseq.

**Comment by sravan953** [comment]
Hi @tonggehua ! Thanks for being (super) patient! Commit 505889cdacc030071a5b0325d50fa180ce83fc90 addresses this - `add_gradients.py`. Take a look - https://github.com/imr-framework/pypulseq/blob/505889cdacc030071a5b0325d50fa180ce83fc90/pypulseq/add_gradients.py
