### ISSUE TITLE
UnboundLocalError in make_sinc_pulse.py

### ISSUE THREAD

**Issue by schuenke** [imr-framework/pypulseq#46]
Since https://github.com/imr-framework/pypulseq/commit/7542b39630c1c4cefc6eb5ded3ddb290a54e487c I get the error `UnboundLocalError: local variable 'gz' referenced before assignment` when creating an rf pulse with make_sinc_pulse.py. 

This happens when I set `return_gz = False` or when I don't set any return_gz value and thus use the False default value.

**Comment by sravan953** [comment]
Please let me know if pulling from the latest `dev` commit fixes this issue for you.

**Comment by schuenke** [comment]
The 
```
    if return_gz:
        return rf, gz, gzr
    else:
        return rf
```

fixed the issue.

For consistency I would use the same if-else style in the **_make_gauss_pulse.py_** as well.


Very minor thing:
the default for return_gz is **_False_**, but the docstring reads `return_gz:bool, default=True`

**Comment by sravan953** [comment]
Thanks @schuenke for bearing with me. The latest commits must have fixed this for good!

**Comment by schuenke** [comment]
Issue is fixed now. Thanks @sravan953 !
