### ISSUE TITLE
Return values of make_xxx_pulse functions

### ISSUE THREAD

**Issue by schuenke** [imr-framework/pypulseq#47]
Since https://github.com/imr-framework/pypulseq/commit/7542b39630c1c4cefc6eb5ded3ddb290a54e487c the make-pulse-functions like _make_sinc_pulse.py_ and _make_gauss_pulse.py_ return a different number of variables as before when using `return_gz = False`. 

For compatibility with previous versions I suggest to return Nones for _gz_ and _gzr_ as it was the case before the release of v1.3.1. However, I think using the _return_gz' flag instead of the try block is a good idea and I suggest to change the return lines only. For example the _make_sinc_pulse.py_ could be modified to:

```    
if return_gz:
    return rf, gz, gzr
else:
    return rf, None, None
```

This would also solve issue https://github.com/imr-framework/pypulseq/issues/46

Let me know if I should include this in the PRs for issue https://github.com/imr-framework/pypulseq/issues/46 and issue https://github.com/imr-framework/pypulseq/issues/48.

**Comment by sravan953** [comment]
I guess the return function executes irrespective of the `return_gz` value, missed this! I will work on this fix, and incorporate your suggested changes, consequently fixing #46.

**Comment by sravan953** [comment]
Please let me know if pulling from the latest `dev` commit fixes this issue for you.

**Comment by sravan953** [comment]
Thanks @schuenke for bearing with me. The latest commits must have fixed this for good!

**Comment by schuenke** [comment]
Issue is fixed now. Thanks @sravan953 !

**Comment by schuenke** [comment]
Hey @sravan953,
will you merge this fix and the others from the dev branch into master and create a new release soon?

**Comment by sravan953** [comment]
Hi, yes! I commit to publishing a new release by Friday (04/30). Thanks for bearing with me!

**Comment by schuenke** [comment]
Will this be 1.3.1post1 than? We need to submit the proofs of our paper by tomorrow and I would lile to mention the release.

**Comment by sravan953** [comment]
Yes `1.3.1post1`

**Comment by sravan953** [comment]
@schuenke Hi, published!

**Comment by schuenke** [comment]
Thanks @sravan953 . Will test it tomorrow 👍

**Comment by schuenke** [comment]
Seems to work fine. Thanks.
