### ISSUE TITLE
ValueError in make_block_pulse.py when not difining the use parameter

### ISSUE THREAD

**Issue by schuenke** [imr-framework/pypulseq#48]
Since https://github.com/imr-framework/pypulseq/commit/7542b39630c1c4cefc6eb5ded3ddb290a54e487c the _make_block_pulse.py_ throws the ValueError `ValueError: Invalid use parameter. Must be one of 'excitation', 'refocusing' or 'inversion'. Passed: ` when _use_ is not defined. The reason is that the default for _use_ is an empty string now, but in line 64 you check for a _None_. This can be fixed by changing line 64 to:

`if use != '' and use not in valid_use_pulses:`

**Comment by sravan953** [comment]
Please let me know if pulling from the latest `dev` commit fixes this issue for you.

**Comment by schuenke** [comment]
Unfortunately you forgot to add a `return` in the else statement. It must be 
```
    if return_gz:
        return rf, gz
    else:
        return rf
```

instead of

```
    if return_gz:
        return rf, gz
    else:
        rf
```

**Comment by sravan953** [comment]
Oh darn, oops, will fix.

**Comment by schuenke** [comment]
Issue is fixed now. Thanks @sravan953 !
