### ISSUE TITLE
Previous working TSE script generates error

### ISSUE THREAD

**Issue by tonggehua** [imr-framework/pypulseq#51]
**Describe the bug**
I tried to run the TSE notebook that previously worked under the version 1.2.0post4; with the current 1.3.1post1, it produces an error at the first make_sinc_pulse

**To Reproduce**
- Go to write_tse.ipynb: https://github.com/tonggehua/mr-sequence-validation/blob/main/TSE/write_tse.ipynb
- Run the code with PyPulseq 1.3.1post1 or master at installation 

**Expected behavior**
This error should happen at the very first `make_sinc_pulse`:
```
    rf_ref, gz, _ = make_sinc_pulse(flip_angle=flip_ref, system=system, duration=t_ref, slice_thickness=thk,
TypeError: cannot unpack non-iterable types.SimpleNamespace object
```
**Desktop (please complete the following information):**
 - OS: Windows 10 
- `pypulseq` version: 1.3.1post1

**Comment by sravan953** [comment]
Hi! Please try passing `return_gz=True` to the `make_sinc_pulse()` call, that should fix your issue. Let me know!

**Comment by tonggehua** [comment]
That worked. Should this be part of the release notes?
