### ISSUE TITLE
Typo in make_arbitrary_rf

### ISSUE THREAD

**Issue by sairamgeethanath** [imr-framework/pypulseq#57]
Line 72: signal = signal / bp.abs(np.sum(signal * system.rf_raster_time)) * flip_angle / (2 * np.pi) 

Change bp to np

**Comment by sravan953** [comment]
This was fixed in commit 2548f0deb3662dd75556af202b5141335b0edb7d on the `dev` branch. A future stable release will incorporate these changes on the publicly available PyPI package.
