### ISSUE TITLE
seq.read does not support read of previous versions of '.seq' files

### ISSUE THREAD

**Issue by ZemaTimoteo** [imr-framework/pypulseq#6]
Regarding the 'seq.read()' function we realze that we could not read '.seq' files that were created with previous versions of the pypulseq toolbox. This means that we had to generate the '.seq' file again with the latest version of the pypulseq toolbox, in order to read it.

**Comment by sravan953** [comment]
Currently, this is an intended design choice.
Reading a newer `.seq` file with an older version of `pypulseq` is definitely to be avoided.
Future versions of `pypulseq` will be compatible with the versions before.
Apologies for the inconvenience.
