### ISSUE TITLE
Wrong time unit in function documentation

### ISSUE THREAD

**Issue by mavel101** [imr-framework/pypulseq#63]
The time unit in the description of more or less all event block objects (such as pulses, gradients,...) is wrong. The time unit in PyPulseq is seconds [s] instead of milliseconds [ms] as stated in the descriptions. This might be confusing especially for new users.

**Comment by sravan953** [comment]
Thanks @mavel101 ! Will fix.

**Comment by imr-framework** [comment]
Hi @mavel101 ! Commit cc4aa8d4a50b2a17d4e375306d5d322e70ceac75 should fix this, thanks for bring this up!

**Comment by sravan953** [comment]
Hi @mavel101 ! Commit https://github.com/imr-framework/pypulseq/commit/cc4aa8d4a50b2a17d4e375306d5d322e70ceac75 should fix this, thanks for bring this up!
