### ISSUE TITLE
Function to appends the md5_hash signature to the .seq file to make it compatible with pulseq Version 1.4

### ISSUE THREAD

**Issue by Nikbert** [imr-framework/pypulseq#64]
**Is your feature request related to a problem? Please describe.**
Pulseq Version 1.4 requires a md5_hash signature at the end of the .seq file

**Describe the solution you'd like**
A function that appends the signature to make the .seq file compatible with Pulseq V1.4.
Calling the function "add_signature.add_md5_sig(file_name)" after the "seq.write()" function will append the required signature. 

**Describe alternatives you've considered**
An alternative would be to include the function in the seq.write function.
This would be the preferred solution in the future.

There is a pull request for the described add_signature.py function

**Comment by sravan953** [comment]
Hello @Nikbert ! Thanks for opening this issue + the PR! I am already working on this and hope to push out PyPulseq 1.4.0 soon! Stay tuned! :)

**Comment by imr-framework** [comment]
Hi @Nikbert , thanks for being patient! Commit f36f91a7dd7ff7c0b37ce0f559312c918f63afe4 adds this functionality. Take a look - https://github.com/imr-framework/pypulseq/blob/f36f91a7dd7ff7c0b37ce0f559312c918f63afe4/pypulseq/Sequence/write_seq.py#L245

**Comment by sravan953** [comment]
Hi @Nikbert , thanks for being patient! Commit https://github.com/imr-framework/pypulseq/commit/f36f91a7dd7ff7c0b37ce0f559312c918f63afe4 adds this functionality. Take a look - https://github.com/imr-framework/pypulseq/blob/f36f91a7dd7ff7c0b37ce0f559312c918f63afe4/pypulseq/Sequence/write_seq.py#L245
