### ISSUE TITLE
Indexing issues happen during seq.read ()

### ISSUE THREAD

**Issue by tonggehua** [imr-framework/pypulseq#7]
In line 158 - 171 of `sequence.py`, the code tries to access an index that is out of range in `lib_data` and causes an error when one calls `seq.read()` on a file created by the same PyPulseq version (1.2.1).

Those indices should change from n to n - 1.

**Comment by sravan953** [comment]
Fixed in ea8059e88fd93c1690c7a69430a8a48101c7d8f1.
