### ISSUE TITLE
Wrong default duration in make_trapezoid

### ISSUE THREAD

**Issue by schuenke** [imr-framework/pypulseq#70]
**Describe the bug**
With b5bd54ad6078f974373291c06bbb510993eb3009 the default duration of make_trapezoid() was changed from 0 to 4e-3. However, the make_trapezoid() function is often used to create a rephasing gradient (usually named gzr) with minimum duration. This does not work anymore, because it's always using the default duration of 4e-3 now leading to much larger minimum echo times etc

**To Reproduce**
- create an rf pulse (e.g. using pp.make_sinc_pulse()) and set return_gz = True
- check the duration of the rephasing gradient (gzr) using pp.calc_duration() 

**Expected behavior**
Calling make_trapezoid() without specifying a duration should create a gradient with minium possible duration

**Solution to fix the problem**
Change the default duration back to 0.

**Comment by sravan953** [comment]
Hopefully the latest commit fixes things!
