### ISSUE TITLE
Possible typo in make_arbitrary_rf.py 

### ISSUE THREAD

**Issue by tblazey** [imr-framework/pypulseq#82]
Line 72 of make_arbitrary_rf.py is:

signal = signal / bp.abs(np.sum(signal * system.rf_raster_time)) * flip_angle / (2 * np.pi)

I'm assuming 'bp' is supposed to be 'np'

**Comment by tblazey** [comment]
Also, I think you need parentheses around 'rf, gz' in line 124. Write now it reads:

return rf, gz if return_gz else rf

which returns two copies of rf.

**Comment by sravan953** [comment]
@tblazey I am not able to find this typo even as early as commit 5ca1035c79b626cf3a13beb2bd487be891d56667 (which was the latest commit at the time you opened this issue, 11 days ago). Did you pull the latest `dev` version? Also, the return statements between lines 144-147 should avoid any duplicate returns. If you are still facing that problem on the latest version, could you share code so I can reproduce the bug on my end?
