### ISSUE TITLE
About changing the position and size of saturation band, fov etc. during scanning

### ISSUE THREAD

**Issue by Michaelsqj** [imr-framework/pypulseq#91]
Dear developers,

Thank you very much for sharing this useful tool. It's a shame that I still haven't got interpreter from Siemens yet, and I never had a chance to try it. However, I'm wondering, if everything is fixed, how do we change the size and position of saturation band, fov, coil settings etc. during scanning? I suppose that we couldn't know the exact number of these parameters until subject is in the scanner right? How are we supposed to set these parameters then?

Cannot be more grateful if anyone has any advice!

Yours,
Qijia

**Comment by bilal-tasdelen** [comment]
Answered in [https://github.com/pulseq/pulseq/issues/18](https://github.com/pulseq/pulseq/issues/18).
